- name: configure payment server
  hosts: payment
  become: yes
  tasks:
  - name: install python
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - python
    - gcc
    - python3-devel

- name: install dependencies
  ansible.builtin.pip:
    requirements: requirements.txt
    executable: pip3.9
  args:
    chdir: /app